### ISSUE TITLE
User not Found Exception

### ISSUE THREAD

**Issue by S3cur3Th1sSh1t** [fox-it/Invoke-ACLPwn#1] opened 2018-04-27 12:55 UTC
I Get The Following Exception in the parsing process.

[*]     Found 4882 ACLs
[*]     Parsing ACL. This might take a while...
[Get-DistinguishedNameForObject] User not found.
In C:\Invoke-ACLPwn-master\Invoke-ACLPwn-master\Invoke-ACLPwn.ps1:144 Zeichen:9
+         throw '[Get-DistinguishedNameForObject] User not found.'
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: ([Get-Distinguis...User not found.:String) [], RuntimeException
    + FullyQualifiedErrorId : [Get-DistinguishedNameForObject] User not found.

Some ideas, how to fix this?

**Comment by rindert-fox** [comment] 2018-04-27 18:41
Can you replace `throw [Get-DistinguishedNameForObject] User not found.'` with 
`throw "[Get-DistinguishedNameForObject] Object '$($obj)' not found."`?

That should give you the input object that was queried. Can you manually query the object to see what kind of object it is? (user, group, computer, etc?)

**Comment by S3cur3Th1sSh1t** [comment] 2018-04-30 07:27
I changed the line and tried one more run:
Object 'Administrators@testdomain.net' not found.

Maybe the @ causes problems here?

**Comment by S3cur3Th1sSh1t** [comment] 2018-04-30 09:05
I just did some Debugging. The @ is definitely not the problem.
The first three Groups get parsed correctly. The fourth Group 'administrators@testdomain.net' has no result in the dirsearcher.FindOne() Query. 

The LDAP Filter seams to be correct. The $dirsearcher variable looks like this:

CacheResults             : True
ClientTimeout            : -00:00:01
PropertyNamesOnly        : False
Filter                   : (&(|(objectClass=group)(objectClass=user))(|(sAMAccountName=Administrators)(sAMAccountName=Administrators@testdomain.net)(userPrincipalName=Administrators@testdomain.net)))
PageSize                 : 0
PropertiesToLoad         : {distinguishedName, ADsPath, distinguishedName}
ReferralChasing          : External
SearchScope              : Subtree
ServerPageTimeLimit      : -00:00:01
ServerTimeLimit          : -00:00:01
SizeLimit                : 0
SearchRoot               : System.DirectoryServices.DirectoryEntry
Sort                     : System.DirectoryServices.SortOption
Asynchronous             : False
Tombstone                : False
AttributeScopeQuery      : 
DerefAlias               : Never
SecurityMasks            : None
ExtendedDN               : None
DirectorySynchronization : 
VirtualListView          : 
Site                     : 
Container                :

**Comment by S3cur3Th1sSh1t** [comment] 2018-04-30 09:24
Additional Information: There is no Group named 'Administrators' in the Testdomain - only the german word for it: 'Administratoren'.  I could find the SID but not the name administrators.

**Comment by rindert-fox** [comment] 2018-04-30 10:14
Hi there,

To understand the problem correctly: Does the SID of the `Administratoren` group end with 500? 
My planning is to release a fix for this issue this week. Thanks for debugging it so far!

**Comment by S3cur3Th1sSh1t** [comment] 2018-04-30 11:24
HI,
the SID for the _Administratoren_ Group is : S-1-5-32-544
Thats your _Administrators_ Group from the knownSids Hashtable.

Thanks for the fast replies :)

**Comment by rindert-fox** [comment] 2018-04-30 11:29
Thanks, will fix this issue this week!

**Comment by rindert-fox** [comment] 2018-05-03 10:32
Hm, I cannot reproduce the problem. The script uses the output that is created by sharphound; the knownSids hashtalbe is currently not used.

Can you create an export manually with sharphound (`sharphound.exe -d <domain_name> -c acl`) and check if there's another identity/object in your AD with the name `administrators`?

**Comment by S3cur3Th1sSh1t** [comment] 2018-05-09 11:31
The Sharphound.exe output seams to be the problem. The Sharphound Output uses english words for german spelled groups. In the csv-File is a group called administrators, but in the domain is no object with this name.
I manually changed the Group-Name in the sharphound output file with the german ones and added a static Path for the $aclPath variable to the file with renamed groups.

The Script works now. So its no problem with your script.

**Closed as completed** 2018-05-14 07:38 UTC

**Comment by frennkie** [comment] 2018-05-15 15:06
I ran into a similar issue. I have access to a domain joined system but are unable to run Sharphound.exe on it. But I was able to create the Sharphound acls.csv elsewhere. So now I replaced ``$aclPath = Get-SharpHoundACL ...`` with ``$aclPath = "acls.csv"``. 

So it might make sense to provide a commandline option for passing in the CSV file instead of running Sharphound.exe, what do you think?

**Comment by init5-SF** [comment] 2019-12-11 17:32
hello, I am having the same issue.
I used `throw "[Get-DistinguishedNameForObject] Object '$($obj)' not found."` and the problematic entity appeared to be 'Anonymous@testdomain.local'
This is sharphound.exe 2.1.0

Any ideas? :)
